# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c59d59bdd89ca2423c1761f582cf201ebb5ad65853797ba4e8a22793825d124adfdbb4c7d01e3c8a48d4540ad3a49e5ce19461e5465fc9b275907b6acf08408f

test:
  secret_key_base: 50d1f9393f3cb74e3af06a1571935720e5f237c0059558e552657da684a7dac9627aa056bea8950aae50730e905fbf1a2c0ce78a9d02ba59013a7771519d7664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
